###vf和glsl调用时互不干扰
###vf的补帧脚本只能同时启用一个，启用另一个前先关闭其他，你可以在i键的第一页看到vf的启用列表
###即使之前已启用KrigBilateral，进行glsl的覆盖式替换后，需要再次按键来启用KrigBilateral。你可以在i键的第二页看到glsl的启用列表
###a4k中部分滤镜如出现绿屏/黑屏之类的画面错误，后端换d3d11成vulkan测试

##############
## glsl列表 ##
##############

#启用/关闭 高级cscale色度升频
CTRL+1 change-list glsl-shaders toggle "~~/shaders/KrigBilateral.glsl"
#覆盖式替换：ACNet推荐滤镜方案
CTRL+2 change-list glsl-shaders set "~~/shaders/ACNet_HDN_L1.glsl"
#覆盖式替换：FSRCNNX推荐优化算法
CTRL+3 change-list glsl-shaders set "~~/shaders/FSRCNNX_x2_8-0-4-1_LineArt.glsl"
#覆盖式替换：anime4k推荐滤镜方案（大幅改变观感）
CTRL+4 change-list glsl-shaders set "~~/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl;~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_Deblur_DoG.glsl;~~/shaders/Anime4K_DarkLines_HQ.glsl;~~/shaders/Anime4K_ThinLines_HQ.glsl;~~/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"

#清空所有glsl滤镜
CTRL+` change-list glsl-shaders clr ""


##############
##  vf列表  ##
##############

#启用/关闭 mvtools补帧通用版
CTRL+6 vf toggle vapoursynth="~~/mvtools-standard.vpy"
#启用/关闭 mvtools补帧进阶版（慎用）
CTRL+7 vf toggle vapoursynth="~~/mvtools-high.vpy"

#清除所有vf滤镜
CTRL+0 vf clr ""
