events {}

http {
	keepalive_timeout 30;
	client_max_body_size 100m;
	server_names_hash_max_size 512;
	server_names_hash_bucket_size 1024;
	ssl_certificate dom0.crt;
	ssl_certificate_key dom0.key;
	proxy_buffering off;
	access_log off;
	include dom0.conf;
}